### ISSUE TITLE
Fill base model with translated attributes automatically 

### ISSUE THREAD

**Issue by vinkla** [vinkla/translator#1]
Currently you have to add the translated values to the `$appends` array and create a [mutator](http://laravel.com/docs/4.2/eloquent#accessors-and-mutators) on the base model to fetch the translated attributes. This is not ideal. Instead we want to have a way to set the attributes on the base model automatically. Maybe with the `setAttributes` method that exists on our Eloquent objects.

**Comment by alexanderweiss** [comment]
I assume you are referring to converting a model to an array or JSON? Because getting an attribute on the base model (e.g. book->name) does return a translated version.

**Comment by vinkla** [comment]
Yeah, that is true. Though, lets say you return the entire `$book` object like this `return $book`. Then the translated fields wont be fetched.
