### ISSUE TITLE
Translator and Baum

### ISSUE THREAD

**Issue by broszies** [vinkla/translator#15]
Hi, just a short question: Does anyone have any experience in using the translator in conjunction with the Baum nested set model for Laraval?

Regards

Wolf

**Comment by vinkla** [comment]
Hey Wolf, could you please explain a bit more? Maybe with an example code snippet?

**Comment by broszies** [comment]
Hi,
I think my problem is with Baum, not with the translator, I have posted in Baums repository (https://github.com/etrepat/baum/issues/144)
 and will get back with an issue if i can pinpoint the problem. You can close this issue, and sorry for bothering you.
Regards!

**Comment by illuminate3** [comment]
I'm having the issue of just getting the model to start ...


use Illuminate\Database\Eloquent\Model;

//use Laracasts\Presenter\PresentableTrait;
// use Vinkla\Translator\Translatable;
// use Vinkla\Translator\Contracts\Translatable as TranslatableContract;

use Baum\Node;
use Cache;

class Page extends Node {
//class Page extends Node implements TranslatableContract {

//  use Translatable;
//  use PresentableTrait;
I had to comment out the Translator package to use my model again.

Here's the error that I'm getting.

Page::__toString() must not throw an exception
Has anybody got Baum 1.* to work with this package?
