### ISSUE TITLE
Translator and Baum II

### ISSUE THREAD

**Issue by broszies** [vinkla/translator#18]
Hi, me again.
Problem: Translations do not get saved into the database table OR Baum values do not get saved in the database.

--------------
The Model:
--------------
// app/models/Category.php
use Baum\Node;
use Vinkla\Translator\TranslatorTrait;

/**
* Category
*/
class Category extends Node {
   use TranslatorTrait;
  /**
   * Table name.
   *
   * @var string
   */
  protected $table = 'categories';

   protected $fillable = ['name', 'description'];

    /**
     * @var string
     */
    protected $translator = 'CategoryTranslation';

    /**
     * @var array
     */
    protected $translatedAttributes = ['name', 'description'];

-------------------
The Controller:
-------------------

	public function store()
	   {
      //Store created category in database
      $id = Input::get('category');
      $input = Input::all();
      $validation = Validator::make($input, Category::$rules);
        if ($validation->passes())
            {
              $category = new Category;            
              $category->parent_id    = Input::get('parent_id');
              $category->name         = Input::get('name');
              $category->description  = Input::get('description');
              $category->save();
            return Redirect::route('categories.index')
            ->with('message', trans('categories.success_create'));
            }
        return Redirect::route('categories.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', trans('validation.error'));
	   }
 
The result: My app produces a success message, but the translations are not in the database, and if I call categories.index again the dataset does not have a name or description.
If I car_dump the output instead, the result is a nice array with all necessary values in it, so the trouble has to be in the controller.

If I use the following controller as an alternative: (snippet)

       if ($validation->passes())
            {
            Category::create($input);
            return Redirect::route('category.index')
            ->with('message', trans('category.success_create'));

the translations get saved, but the Baum-fields do not get updated. Reason is with Baum, all NestedSet-related fields are guarded from mass-assignment by default.

Changing the default by specifying 

protected $guarded = array('id', 'lft', 'rgt', 'depth');

does not change anything.

Any idea?

Regards

Wolf

**Comment by vinkla** [comment]
What version are you using?

**Comment by broszies** [comment]
I am using 1.3.0.
Does it make sense to switch to 2.0 already, or should I wait until Laravel 5.0 is out for that?

**Comment by vinkla** [comment]
Laravel 5 is out now. [Here is an upgrade guide.](http://laravel.com/docs/master/upgrade#upgrade-5.0) Depends on wether you are going to upgrade to Laravel 5 or not. Version 2.0 only support Laravel 5.

**Comment by vinkla** [comment]
I've never tried to use Baum with Laravel. What I can see is that your `Category` models extends `Node`. Is this an Eloquent object? This package depends on Laravels Eloquent object.

**Comment by broszies** [comment]
Hi,
I might give an early upgrade a try, though I am bit weary of breaking things. The "Node" Model extends the Eloquent Model, however, i am not sure that this is the source of the problem. The problem might be how Baum interacts with Laravel as described here https://github.com/dimsav/laravel-translatable/issues/25

I could fix the problem by switching to a different translator package it seems, but I would like to continue yours :) I will try the code presented in the issue I linked and see if I can adapt it to your translation package. 

Should anyone else be successfull in using Baum with the vinkla translator, I would be happy to hear how they did that.

Best regards

Wolf

**Comment by vinkla** [comment]
Great! Then we know problem lies within how Baum interacts with Eloquent and not how this package works. Let me know how it goes and if you succeed to integrate Baum with the Translator.

**Comment by broszies** [comment]
Will do - thanks for the information!
