### ISSUE TITLE
Help form

### ISSUE THREAD

**Issue by larsurilch** [vinkla/translator#21]
Hello Vicent,

First I would like to congratulate you for the excellent component. My question is how to relate two translations with the parent table from a form? I have the apartment table and the table and apartment_translations attached form

![tela](https://cloud.githubusercontent.com/assets/251246/6652217/a468bd2a-ca46-11e4-893d-8ad4916d9fd9.png)

How have you implemented the relationship will always be one to one. Sorry for my bad english.

```php
public function store(ApartmentRequest $request) {
  App::setLocale($request->input('language'));
  $this->apartment->create($request->all());
}
```

Thanks

**Comment by vinkla** [comment]
Thanks. Glad you like it!

The first time you save your translation it uses the current set language/locale. When you want to translate it to other languages you'll have to load it from the database, set another language and save it again. There are currently no way to translate multiple translations at once.

**Comment by larsurilch** [comment]
Thanks Vicent,

Managed to solve but it was not good.
Now I have problem in edit. The id is setted the parent table as the image

![edit](https://cloud.githubusercontent.com/assets/251246/6653143/0c209df2-ca65-11e4-8231-0af292f3db54.png)

In RouteServiceProvider.php
```php
public function boot(Router $router) {
   parent::boot($router);

   $router->model('categories', 'App\Category');
}
```

In CategoriesController.php
```php
public function edit(Category $category) {
  App::setLocale($category->language);
  $languages = $this->languages();
  return view('categories.edit', compact('category', 'languages'));
}
```

Is there a tutorial where you have a simple CRUD with the component ?

Thanks

**Comment by vinkla** [comment]
There is no tutorial out yet. But I've setup an example project take a look at this [ArticleController.php](https://github.com/vinkla/translator-example/blob/master/app/Http/Controllers/ArticleController.php)
