### ISSUE TITLE
Seeder for testing

### ISSUE THREAD

**Issue by larsurilch** [vinkla/translator#22]
Hello Vincent,

Would provide a simple example of a seeder for testing? For example, a model Country.php with $translatedAttributes = name.

Thanks

**Comment by vinkla** [comment]
There is an article seeder in the example application https://github.com/vinkla/translator-example

**Comment by vinkla** [comment]
How do you mean? For languages or the tables you want to translate?

**Comment by larsurilch** [comment]
For a table that I want to translate.

**Comment by vinkla** [comment]
There are examples for both base and translations table in the README https://github.com/vinkla/translator#migrations

**Comment by larsurilch** [comment]
I think I expressed myself wrong. In fact I wonder if you can do something like this?

```php
$data = [
    'en'  => array('name' => 'Greece'),
    'pt'  => array('name' => 'Grecia'),
];

Country::create($data);
```

**Comment by vinkla** [comment]
Currently you can't. You can solve it with a loop.

```php
$translations = [
    'en'  => array('name' => 'Greece'),
    'pt'  => array('name' => 'Grecia'),
];

foreach ($translations as $locale => $translation) {
    App::setLocale($locale);
    Country::create($translation);
}
```

**Comment by larsurilch** [comment]
The problem with this seeder that the data are not related.

table countries
id - 1
id - 2

table country_translations

id - 1, country_id - 1
id - 2, country_id - 2

The correct thing so

table countries
id - 1

table country_translations

id - 1, country_id - 1
id - 2, country_id - 1

**Comment by vinkla** [comment]
Your `country_translations` should have a `country_id` and a `locale_id` column. Could you maybe paste your migrations for the countries and the locales table?

**Comment by larsurilch** [comment]
```php
Schema::create('locales', function(Blueprint $table)
{
   $table->increments('id');
   $table->string('language', 2);
   $table->timestamps();
});
```

```php
Schema::create('countries', function(Blueprint $table)
{
   $table->increments('id');
   $table->timestamps();
});
```
```php
Schema::create('country_translations', function(Blueprint $table)
{
  $table->increments('id');
  $table->string('name', 35);
  $table->integer('country_id')->unsigned()->index();
  $table->integer('locale_id')->unsigned()->index();
  $table->timestamps();

  $table->foreign('country_id')->references('id')->on('countries')->onDelete('cascade');
  $table->foreign('locale_id')->references('id')->on('locales')->onDelete('cascade');

  $table->unique(['country_id', 'locale_id']);
});
```

**Comment by vinkla** [comment]
Everything looks fine. Could you describe in more detail what is not working?

**Comment by larsurilch** [comment]
After running the seeder in the database the result looks like this

countries table

id | created_at | updated_at
------------ | ------------- | -------------
1 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09
2 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09

country_translations table

id | name | category_id | locale_id | created_at | updated_at
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | Greece | 1 | 1 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09
2 | Grécia | 2 | 2 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09

That way we do not have the relationship of one to many. The expected should be

countries table

id | created_at | updated_at
------------ | ------------- | -------------
1 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09

country_translations table

id | name | category_id | locale_id | created_at | updated_at
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | Greece | 1 | 1 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09
2 | Grécia | 1 | 2 | 2015-03-14 18:49:09 | 2015-03-14 18:49:09

**Comment by vinkla** [comment]
Ahh okay, I see what you're trying to tell me. Could you paste your models as well?

**Comment by larsurilch** [comment]
Locale.php
```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Locale extends Model {

    protected $fillable = ['language'];

}
```

Country.php
```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

use Vinkla\Translator\Translatable;
use Vinkla\Translator\Contracts\Translatable as TranslatableContract;

class Country extends Model implements TranslatableContract {

    use Translatable;

    protected $fillable = ['name'];

    protected $hidden = ['created_at', 'updated_at'];

    protected $translator = 'App\CountryTranslation';

    protected $translatedAttributes = ['name'];

    protected $appends = ['name'];

    public function getNameAttribute()
    {
        return $this->name;
    }

}
```

CountryTranslation.php
```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class CountryTranslation extends Model {
}
```

**Comment by vinkla** [comment]
I'll take a look at it and come back to you when I've tested it myself.

**Comment by vinkla** [comment]
Hey @larsurilch, I've just tried running the [example application](https://github.com/vinkla/translator-example) and it works fine. Have you had time to look at it?
