### ISSUE TITLE
Cache translated attributes

### ISSUE THREAD

**Issue by iaguilera** [vinkla/translator#23]
It seems that each time I access a translated propierty, a query to database is executed to obtain the property value. If I get the same property 3 times sequentially, 3 times the query is being executed.

I thing it would be nice to cache the translated values, so only is necessary one query to the database.

Thanks.

**Comment by vinkla** [comment]
thanks for reaching out. Thats a good idea! Though, I currently don't have much time to spare. Maybe you could submit a pull request?

**Comment by iaguilera** [comment]
It seems that your code in getTranslation function, now checks the existence of $this->translation (cached value?), and if not exists, query the database, but then doesnt assign the value to $this->translation.
I think is only needed to add one line:
CHANGE:
if ($translation) { return $translation; }
MUST BE:
if ($translation) { 
       $this->translation = $translation;
       return $translation; 
}

I tried and seems to work

**Comment by vinkla** [comment]
Could you submit a PR?

**Comment by iaguilera** [comment]
I tried to submit the PR... is the first time I do, hope is ok.

**Comment by vinkla** [comment]
Thanks for your PR. It has been merged!

**Comment by vinkla** [comment]
Added here https://github.com/vinkla/translator/releases/tag/2.0.1

**Comment by iaguilera** [comment]
Thanks, love your plugin great job :-)

**Comment by vinkla** [comment]
Thanks :)
