### ISSUE TITLE
Search by SLUG

### ISSUE THREAD

**Issue by cloudstudio** [vinkla/translator#30]
Hi, thanks for this awesome package !

I use Article::find($id); and work.

But i need search for language SLUG.

I try this : Article::where('slug','=',$slug')->get(); but sure not work, 

Unknown column 'slug' in 'where clause' (SQL: select * from `articles` where `slug` = test)

I have "slug" field in article_translations, but i dont know how search for translation slug

Any ideas?

**Comment by vinkla** [comment]
Hey @cloudstudio, glad you like it!

I guess you want the `slug` to be static and not a unique one for each language? Do you want the slug to be translated in each language?

If I were you, I would add a `slug` column on the `articles` table instead. The `slug` column would contain the `title` attribute from default language in "sluged" version.

When saving I would do something like this:

```php

$article = new Article();

 // This is saved in the article_translations table
$article->title = $title;

// This is saved in the articles table
$article->slug = Str::slug($title);

$article->save();
```

Do you think that will work for you?

**Comment by illuminate3** [comment]
Hi,
I'm going to add here instead of a new issue.

I was planning of using https://github.com/cviebrock/eloquent-sluggable but it looks like they are in conflict. I want to be able to have translated slugs.

What would you suggest?

**Comment by vinkla** [comment]
You'll have to create an extra column on your translation table called `slug`. Though are you going to use it for URLs?

**Comment by illuminate3** [comment]
I'm working on a CMS for part of "platform" system. https://github.com/illuminate3/himawari (I've commented out the cviebrock package in my model for the moment.)

I've done that but when I add the sluggable package to my main Model it errors out since it doesn't see the slug column in the ModelTranslation table.

Yes, I plan to have translated slugs.

Thanks!

**Comment by vinkla** [comment]
Then your translated pages will have unique URLs. That can both be good and bad. Depending on what content you have. Google will handle them as multiple pages in their search.

**Comment by GrahamCampbell** [comment]
Multiple urls for the same resource is normal a bad idea.

**Comment by illuminate3** [comment]
Thanks guys.

I guess for most purposes the content is just being translated rather than being different besides the differences that naturally occur in languages.

I'll just go with a single url-slug pattern.
