### ISSUE TITLE
Is it possible to fetch a list like so Article::lists('title', 'id')?

### ISSUE THREAD

**Issue by slano** [vinkla/translator#32]
Hi,

thanks for the great package, very helpful! A quick question: can I somehow use a new model to fetch a list? Or to perform an order by title like so `Article::orderBy('title')->get();`? So far I'm only able to fetch `Article::all();` which correctly returns all items in the active language. Ordering or fetching a list tries to look for title field in the articles database table.

**Comment by vinkla** [comment]
Hey @slano, glad you like it :) 

You've to first fetch the collection and den return it as a list `Article::all()->lists('title', 'id');`. Please let me know if that works for you.

**Comment by slano** [comment]
Thanks for a swift reply, but unfortunately that doesn't seem to do the trick.

`Article::all()->lists('id')` correctly returns 
array:4 [▼
  0 => "1"
  1 => "2"
  2 => "3"
  3 => "4"]

`Article::all()->lists('title')` returns
array:4 [▼
  0 => null
  1 => null
  2 => null
  3 => null]

`Article::all()->lists('title', 'id')` returns
array:4 [▼
  1 => null
  2 => null
  3 => null
  4 => null] 

But `Article::all()[0]->title` correctly returns the title in active language.

**Comment by vinkla** [comment]
What if you add a [title mutator](http://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators) to the `Article` eloquent model?

**Comment by slano** [comment]
Of course, I forgot about mutator! Works like a charm, thanks for help!

**Comment by vinkla** [comment]
Awesome!
