### ISSUE TITLE
Primary key names

### ISSUE THREAD

**Issue by benjamindk** [vinkla/translator#33]
BUG: Foreign keys are not always named "id", please fix...
- src/Translatable.php (line 234)...
```php
 ->where($this->getForeignKey(), $this->id) 
```
should be:
```php
 ->where($this->getForeignKey(), $this->getKey()) 
```
----------------------------------------------------------------------------------
- src/Translatable.php (line 255)...
```php
return $this->getLocale($locale ?: App::getLocale())->id; 
```
should be:
```php
return $this->getLocale($locale ?: App::getLocale())->getKey(); 
```

**Comment by vinkla** [comment]
Thats true, care to make a pull request?

**Comment by cuviline** [comment]
Wow, thanks @benjamindk !!! @vinkla  please fix it !!! thanks for all :)

**Comment by vinkla** [comment]
I've created a pull request for this #35. Will be added within version 3.0
