### ISSUE TITLE
Form (translatable) Model Binding

### ISSUE THREAD

**Issue by elieandraos** [vinkla/translator#36]
when binding a translatable model to a form in the view (edit case for example), 
the values are not fetched if null is passed in the blade parameter
```
{!! Form::model( $article, ['route' => [...

//blade input for title field , null does not retrieve the value as it should do
 {!! Form::text('title', null, ['class' => 'form-control slug-target']) !!}

//if i set it manually it works
{!! Form::text('title', (isset($article))?$article->title:null, ['class' => 'form-control slug-target']) !!}
```

**Comment by vinkla** [comment]
I'm not sure what your error is? Could you please explain a bit more.

**Comment by elieandraos** [comment]
when you bind a model to a form, (controller@edit) , you don't have to pass the values (loaded from db) in the blade syntax, you pass null as third parameter for an input for example, and laravel is smart enough behind the scenes to load it. (technically fill the input value with the one retrieved from database)

it is not the the case with the article model, as the title field is in the articleTranslation, so i set it manually, Maybe you are right, it is not an error, and i am getting confused.

keep up the good work, i am using your package on a project and it saving me much time :)

**Comment by vinkla** [comment]
Glad you like it :) Let me know if I can help you with anything else.
