### ISSUE TITLE
orderBy on translatedAttributes

### ISSUE THREAD

**Issue by Jaspur** [vinkla/translator#41]
Hi,
How to do an OrderBy for the translatedAttributes. 
For example: "title"-attribute is translatable. 

```Foobar::orderBy('title')->get();``` tells me that title doesn't exist in the Foobar table. That's correct, because it's in foobar_translations. Is there a way to let this work?

**Comment by sven22** [comment]
+1

**Comment by vinkla** [comment]
Currently you have to first fetch the eloquent objects and then order or sort the collection. For more information about Laravel collections, please see: http://laravel.com/docs/5.1/collections#method-sortby

**Comment by sven22** [comment]
Tried that, but that doesn't seem to work. I got the collection and if I tried $collection->sortBy('created_at'); (or any other non-translated field) it does sort my collection as expected. So it seems that sortBy() doesn't have access to the translateble fields yet?

**Comment by vinkla** [comment]
@sven22 Did you add either `->all();` or `->get();` in the end? I guess just calling the `->sortBy()` method only actually sorts the objects?

**Comment by sven22** [comment]
I did:

```php
$projects = Project::orderBy('created_at');
if ($trash) {
	$projects = $projects->onlyTrashed();
}
$projects = $projects->get();

$projects->sortBy('city');
```

**Comment by vinkla** [comment]
What I mean is `$projects->sortBy('city')->all();`.

**Comment by sven22** [comment]
sortBy() seems to be a method for a Collection, when I call it before all() or get() I get an error `Call to undefined method Illuminate\Database\Query\Builder::sortBy()`

**Comment by vinkla** [comment]
Share the code you're using.

**Comment by sven22** [comment]
The method I'm using:

```php
public function overview($trash = false) {
	$projects = Project::orderBy('created_at');
	if ($trash) {
		$projects = $projects->onlyTrashed();
	}
	$projects = $projects->get();

	$projects->sortBy('city');

	return View::make('admin.projects', compact('projects', 'trash'));
}
```

Model:
```php
use Illuminate\Database\Eloquent\Model;
use Vinkla\Translator\Translatable;
use Vinkla\Translator\Contracts\Translatable as TranslatableContract;
use Illuminate\Database\Eloquent\SoftDeletes;
use Config;

class Project extends Model {

	use SoftDeletes, Translatable;

	protected $appends = ['cords'];
	protected $fillable = ['city', 'country', 'lat', 'long'];
	protected $translator = 'App\Models\Locales\ProjectTranslation';
	protected $translatedAttributes = ['city', 'country'];

	/* Rules */
	public static $rules = array(
	);

	/* Relationships */

	/* Appends */
	public function getCordsAttribute() {
		return ($this->lat && $this->long ? str_replace(',', '.', $this->lat) . ', ' . str_replace(',', '.', $this->long) : '');
	}

}
```

Anything else you'd like to see?

**Comment by vinkla** [comment]
Try updating the first snippet to this:

```php
public function overview($trash = false) {
    $projects = Project::orderBy('created_at');
    if ($trash) {
        $projects = $projects->onlyTrashed();
    }
    $projects = $projects->get();

    $projects->sortBy('city')->all();

    return View::make('admin.projects', compact('projects', 'trash'));
}
```

**Comment by sven22** [comment]
Makes no difference unfortunately

**Comment by vinkla** [comment]
Okay, what I wanted to show you was that you can't just call the `sortBy` method except anything after.
