### ISSUE TITLE
Create/Save without mass-assignment

### ISSUE THREAD

**Issue by dtnmr** [vinkla/translator#42]
Hi :smile: 

I keep getting these errors when trying to create a model instance without using mass assignment

``` Creating default object from empty value ```

As I understand the associated translation row is not created in such a case, so how would you create it in a beautiful way ?

Have you planned something like getTranslationOrNew() for the future ?

Thanks a lot,
Martin

**Comment by vinkla** [comment]
I'm not totally sure what you're asking, could you please explain a bit more?

**Comment by dtnmr** [comment]
Hi, sorry for my flimsy explanation, let met try again :stuck_out_tongue: 

So I'm using your package to translate my models, everything worked fine until I had to translate a model of mine that I can't use mass-assignment on, which is basically
```php
Model::create();
```

So what I do to create/save the model is : 

```php
public function createDummyModel()
{
    $dummy = new Dummy();
    
    $dummy->attribute = "This is an attribute of my dummy model.";

    $dummy->save();
}
```

But I'm unable to save the instance because I keep getting `Creating default object from empty value` errors in this case. So I guess the matching translation is not created at this time when not using mass-assignment which results in the error.

So I was looking for a way to check if the related translation exists, and create it if it doesn't.

It is better ? (By the way, apologies for my english, French is my mothertongue :wink: )

**Comment by vinkla** [comment]
Dows your `Dummy` model contain any other attributes except the translated fields?

**Comment by dtnmr** [comment]
Yes it does, but only those I need to translate, the others aren't in the translatedAttributes array.

**Comment by vinkla** [comment]
Have you added all fields (including translated attributes) to the `$fillable` array?

**Comment by dtnmr** [comment]
Yes (But I'm still going to check again),

But isn't the $fillable variable only used when using the ```create()``` method ?

**Comment by vinkla** [comment]
That is correct. What is the purpose of creating an empty object anyway? Note that the `create()` method saves the instance in the background.

**Comment by dtnmr** [comment]
Oh sorry, my previous code was just an example, the model that I'm having problems with is in fact much more complex (It represents a "Board Game" in a shop), in the end I manually set a good dozen of variables (I'm not using mass-assignment on this one because I have to make a lot of modification to the request payload + it made the code look messy as hell)

**Comment by vinkla** [comment]
Okay, could you maybe share the code you have issues with then I could take a look?

**Comment by dtnmr** [comment]
Yes of course !

Here's my model : 
```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Vinkla\Translator\Translatable;
use Vinkla\Translator\Contracts\Translatable as TranslatableContract;

class Game extends Model implements TranslatableContract {

    use Translatable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'games';

    /**
     * @var string
     */
    protected $translator = 'App\Models\Translations\GameTranslation';

    /**
     * @var array
     */
    protected $translatedAttributes = ['name', 'short_description', 'description', 'material', 'video', 'media', 'about'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'slug', 'short_description', 'description', 'avg_players', 'avg_time', 'min_age','author', 'artist', 'material', 'video', 'media', 'about', 'active'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    public function gallery()
    {
        return $this->morphMany('App\Gallery', 'imageable');
    }

    public function category()
    {
        return $this->belongsTo('App\GameCategory', 'category_id');
    }

    public function publisher()
    {
        return $this->belongsTo('App\Publisher', 'publisher_id');
    }
}
```

And the function that I use to create a record of my model (I removed harmless code so it's more legible for you): 

```php
public function postNew()
    {
        $game = new Game;
        $input = Request::all();

        $publisher = Publisher::find($input['publisher']);
        if ($publisher) {
            $game->publisher()->associate($publisher);
        }

        $category = GameCategory::find($input['category']);
        if ($category) {
            $game->category()->associate($category);
        }

        $game->name = $input['name'];
        $game->slug = $input['slug'];
        $game->author = $input['author'];
        $game->artist = $input['artist'];
        $game->min_age = $input['min_age'];
        $game->avg_players = $input['avg_players'];
        $game->avg_time = $input['avg_time'];
        $game->material = $input['material'];
        $game->video = $input['video'];
        $game->media = $input['media'];
        $game->about = $input['about'];
        $game->short_description = $input['short_description'];
        $game->description = $input['description'];
        $game->active = Request::has('active') ? true : false;

        $game->save();
        return redirect('/adm/games');
    }
```

**Comment by vinkla** [comment]
This is the code generating the error?

**Comment by dtnmr** [comment]
Yep, sorry for not mentioning.

**Comment by vinkla** [comment]
No problem. Do you know which line that fails?

**Comment by vinkla** [comment]
When you added the translator package, did you move all translated attributes to the translations table?

**Comment by dtnmr** [comment]
I'm using Whoops and it doesn't give me much informations, apparently that would be this line : 

```php
$game->name = $input['name'];
````

But that doesn't make sense.

Actually, I created them in the translation table, but the fields are still in the base table (I was keeping them as some sort of "backup", so that I could copy it to te translation table afterwards), could it be causing the issue ?

**Comment by vinkla** [comment]
Yeah, could be that. Try removing them.

**Comment by dtnmr** [comment]
Just removed them, still having the error. :/

**Comment by vinkla** [comment]
To bad :/ Here: https://github.com/vinkla/translator/blob/master/src/Translatable.php#L112-L113

**Comment by dtnmr** [comment]
Ok, But this piece of code doesn't seem to get called. as I receive `null` in my case ?

**Comment by dtnmr** [comment]
I was playing a little bit with `php artisan tinker`, apparently the problem occurs when calling this method from Translatable.php for the first time :

```php
    public function setAttribute($key, $value)
    {
        if (in_array($key, $this->translatedAttributes)) {
            return $this->getTranslation()->$key = $value; // Error is thrown here
        }

        return parent::setAttribute($key, $value);
    }
```

Will do a few tests and come back to you !

**Comment by vinkla** [comment]
Cool, let me know how it goes!

**Comment by dtnmr** [comment]
Just had enough of trying to make it work on my complex model so I made a test one with only one attribute, no relations or stuff like that, and : 

```php
$test = new Test;
$test->content = "This is a test";
$test->save();
```

Gives me the same error, can you confirm that this works on your end ?

**Comment by elieandraos** [comment]
@dtnmr show your migrations code. 
i am using this package and it works flawlessly. even on more complex models where i have polymorphic relations and nested sets.

**Comment by dtnmr** [comment]
Here are the migrations for the code above :

```php
class CreateTestTable extends Migration
{
    public function up()
    {
        Schema::create('tests', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::drop('tests');
    }
}
```

```php
class CreateTestTranslationTable extends Migration
{

    public function up()
    {
        Schema::create('tests_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->string('content');

            $table->integer('test_id')->unsigned()->index();
            $table->foreign('test_id')->references('id')->on('tests')->onDelete('cascade');

            $table->integer('locale_id')->unsigned()->index();
            $table->foreign('locale_id')->references('id')->on('locales')->onDelete('cascade');

            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::drop('tests_translations');
    }
}
```

**Comment by michakpl** [comment]
Same here, but it works after I changed line 188 to getTranslation(false), and I'm 100% sure that it worked earlier without this change

    return $this->getTranslation(false)->$key = $value;

**Comment by vinkla** [comment]
Your setup looks fine. We should really get some tests in here. Will try to add some in the next major version. We're open to PRs if any of you find a solution.

**Comment by michakpl** [comment]
And as @dtnmr said it works with Model::create but not when we try to set attributes to object separately and then save it

**Comment by dtnmr** [comment]
Are you using HHVM ? I am using it as FastCGI wrapper, and I have to admit that it has caused me issues (It does not process PHP the same way as other runtimes, so sometimes I had to tweak my code a bit) eversince I started using it.

Maybe this could be related ?

**Comment by elieandraos** [comment]
@dtnmr if it works with Model::create([]) then try to define a mutator in your model 

```
public function setContentAttribute($value)
    {
        $this->attributes['content'] = $value;
    }
```

i didn't test it ... but just throwing a guess.

**Comment by vinkla** [comment]
@elieandraos @dtnmr @michakpl How did it work out on this in the end? Did any of you solve this issue?
