### ISSUE TITLE
Model::lists() method

### ISSUE THREAD

**Issue by atorscho** [vinkla/translator#43]
Greetings,

I need to use `lists()` method for my `<select>` dropdown, but cannot include model's name attribute since it is in an another table.

Right now I am forced to use a `foreach` loop to iterate through the array of elements and return the needed attributes to the array.

Could someone give me a hint in order to implement this idea in a shorter way?

Thanks in advance.

**Comment by vinkla** [comment]
Have you tried adding [http://laravel.com/docs/master/eloquent-mutators](mutators) to the fields you want to list?

**Comment by elieandraos** [comment]
indeed, add a mutator in your model 

```
    //considering title is a translatable field
	protected $appends = ['title'];
	public function getTitleAttribute()
	{
	   return $this->title;
	}
```

**Comment by atorscho** [comment]
I've already tried with mutators before creating the issue, but it didn't work, even with the `appends` property.

**Comment by elieandraos** [comment]
@atorscho then there must be something wrong with your schema/Models.

**Comment by atorscho** [comment]
@elieandraos strange, the translation works, and mutators too, but not in this case.

**Comment by atorscho** [comment]
Resolved! That's not `Model::lists()`, but `Model::all()->lists()`.

**Comment by vinkla** [comment]
:+1:
