### ISSUE TITLE
Fallback translated attribute

### ISSUE THREAD

**Issue by atorscho** [vinkla/translator#45]
I am trying to create multiple forms for each locale. When I repopulate a model that is stored only in English, but the app locale is set to another language (e.g. French), all translatable attributes are null, even with `getNameAttribute()` and other accessors.

Has anybody an idea on how to create a fallback feature?

If `$article->title` is null in current locale, it'll use the fallback locale (usually `en`).

Thanks in advance.

**Comment by vinkla** [comment]
Have you tried setting fallback to true in the configure file?

**Comment by atorscho** [comment]
Can't believe I forgot about this. Should not ask questions at this time. :D Thank you!

**Comment by vinkla** [comment]
It's okay, good that you solved it!
