### ISSUE TITLE
Custom foreign key

### ISSUE THREAD

**Issue by creativeorange** [vinkla/translator#46]
Since I'm using Single Table Inheritance with submodels using the same table, I'm required to manually set the foreign key. Example:

```php
class Question extends Model implements TranslatableContract
{
    use Translatable;

    protected $translatedAttributes = ['question'];

    protected $translator = QuestionTranslation::class;
}

class QuestionTranslation extends Model
{
    protected $table = 'question_translations';
}

class SingleTextbox extends Question {}
```

If i want to create a question through the SingleTextbox class, I receive an error on the foreign key: 'single_textbox_id' not found. Which is correct, since the foreign key is 'question_id'. Is there a way to force the foreign key?

**Comment by vinkla** [comment]
Try adding a custom relation between the translations and the question model:
```php
public function translations()
{
    return $this->belongsToMany(Question::class, $foreignKey, $otherKey);
}
```

**Comment by creativeorange** [comment]
Will try this, but I think the method ```getTranslationByLocaleId``` will fail as well:

```php
$translation = $this->translatorInstance
            ->where('locale_id', $localeId)
            ->where($this->getForeignKey())
            ->first();
```

Maybe it is an idea to add a optional property to the model, e.g. ```$translatableForeign``` like this:

```php
$translation = $this->translatorInstance
            ->where('locale_id', $localeId)
            ->where($this->translatableForeign ?: $this->getForeignKey(), $this->id)
            ->first();
```

and change 
```php
public function translations()
{
    return $this->hasMany($this->translator);
}
```
to:
```php
public function translations()
{
    return $this->hasMany($this->translator, $this->translatableForeign ?: $this->getForeignKey());
}
```

**Comment by vinkla** [comment]
Yeah that could be a solution. We're open to PRs if you feel up to it.

**Comment by creativeorange** [comment]
Thanks. I will give it a try this week. I'm not that much into Git yet, so I will take a look at how to do PRs and then I will come back to this.
For now, thanks for the very quick replies.

**Comment by vinkla** [comment]
No worries, let me know how it goes :)
