### ISSUE TITLE
Overriding save in a model

### ISSUE THREAD

**Issue by schelmo** [vinkla/translator#50]
Hi,
if you override the save (or update, etc.) method in a model, the save method of the Translatable trait isn't called. Perhaps it would be better to override finishSave in the Translatable or using a static bootTranslatable method?

And: Why both update and save are defined in Translatable? Eloquent is using `save()` in its update method.

So i think it would be good to go with `finishSave()`. Then, you also don't have to check for `$saved`.

What do you think?

**Comment by vinkla** [comment]
Any kind of optimization is welcome. I'll keep this here as an reminder. Thanks for your suggestion!

**Comment by vinkla** [comment]
I've implemented this in #52
