### ISSUE TITLE
[Error in source code 3.0.0] fallback set to false always returns null

### ISSUE THREAD

**Issue by ouel92** [vinkla/translator#54]
Hi !
In file `translator/src/Translatable.php` line `49`

###### This block :
```php
if (!$fallback) {
  foreach ($this->translatedAttributes as $attribute) {
    $translation = $this->setAttribute($attribute, null);
  }
}
```
###### Should look more like this :
```php
if (!$translation && !$fallback) {
  foreach ($this->translatedAttributes as $attribute) {
    $translation = $this->setAttribute($attribute, null);
  }
}
```

Otherwise `$article->translate('de', false)->title;` would always return `null` even if the deutsch translation is available in the database

**Comment by vinkla** [comment]
Whoops. That is true. I'll fix this asap.

**Comment by vinkla** [comment]
This is fixed in 3.0.1 now. Thanks for reporting!

**Comment by ouel92** [comment]
Of Course ! Thank you for this package mate ! Great work ! Keep it up :+1:

**Comment by vinkla** [comment]
Thanks :smile:
