### ISSUE TITLE
If i don't want to save automatic translation

### ISSUE THREAD

**Issue by Krato** [vinkla/translator#55]
Hi, I don't want to save automatic translations when i call a Model:create($fields).

How can I do? In the version 2 was a config file, but not in this version.

Thanks!

**Comment by vinkla** [comment]
Doesn't it work as in version 2.0? We haven't changed much when creating new instances.

**Comment by Krato** [comment]
The problem is next.

I have a model with on column that repeats on the translation model. When I save, this column saves on translation table instead the normal table.

An example:

Page-> id, template_id, extras
TranslationPage, id, page_id, locale, content, extras

When I save a new page trought Page::create($fiels), the field $extras saves on page_translation instead page.

Hope you understand :D

**Comment by vinkla** [comment]
Think of the translatable values as columns on the base model. The base model and translation model can't have the same column names. That is probably why it doesn't work.

**Comment by Krato** [comment]
Yes, this is the problem. But with version 2, I can chose not automatic generation of translation. This is not possible on v3 yes?

**Comment by vinkla** [comment]
It should work as the same way as before? What do you mean differ between 2 and 3?

**Comment by Krato** [comment]
Sorry, my mistake. Then no solution yes? I need to change the column. How can I do a no automatic creation of translation, just manual?

**Comment by vinkla** [comment]
Yeah, just manually. Sorry about that.

**Comment by Krato** [comment]
ok, so I will change mu column name. Thanks!

**Comment by vinkla** [comment]
:+1:
