### ISSUE TITLE
Fix for Branch 2.*

### ISSUE THREAD

**Issue by Krato** [vinkla/translator#57]
Hi Vinkla.

Can you update your Package for version 2 with this?

trait Translatable Line 242 change ```->where($this->getForeignKey(), $this->id)``` to:
```
->where($this->getForeignKey(), $this->getKey())
```

This fix the relations issues. If not, when you change config to use fallback language, it doesn't work fine.

I have some packages running this version of translator, but need to fix manuall every time.

Thanks so much.

**Comment by vinkla** [comment]
Please send me PR for this.

**Comment by Krato** [comment]
Sorry, how can i do? I can only set master branch. When I chose 2.2.1 tag I can't create a pull request.

Thanks

**Comment by vinkla** [comment]
Oh yeah, that is right. I forgot I dropped support for older version. Sorry I can help you more. Maybe you can upgrade to the latest version?

**Comment by Krato** [comment]
Pff, no. I have some packages running this version. Is not possible to update just this version to 2.2.2?

**Comment by vinkla** [comment]
It is possible but it would require a lot of work from my side and that is time which I don't have right now.

**Comment by vinkla** [comment]
Sorry. Best thing would be to fork this or upgrade to the new version.

**Comment by Krato** [comment]
OK.Thanks
