### ISSUE TITLE
How can I use a 'locales' table ?

### ISSUE THREAD

**Issue by SirFlyann** [vinkla/translator#58]
Hi, @vinkla. Thanks for sharing this, it helped me a lot =)

I'd like to know how can I use a 'locales' table and set the 'locales' field in the translation table as a foreign key.

**Comment by vinkla** [comment]
When creating the translations table you could add the column locale_id attribute and then require the uniqueness of each row.

**Comment by SirFlyann** [comment]
I've already done that, but the main table keeps trying to find a "locale" instead of "locale_id" in the table, whenever I do a "Table::all()" 

How can I change this query ?
I'm quite new to programming in general, so it could be a simple mistake of mine.

**Comment by vinkla** [comment]
Why can't you use the locale as index instead of locale I'd?

**Comment by SirFlyann** [comment]
Great hint, I wasn't thinking in this way. Going to try it and tell you how it goes. Thanks =)

**Comment by vinkla** [comment]
:+1: Let me know how it goes.

**Comment by SirFlyann** [comment]
Working fine now, thanks.
Just made the locale in the Languages table as index and worked like a charm =)

Thanks for the quick replies and sorry to take your time =)

**Comment by vinkla** [comment]
No worries, glad you solved it.
