### ISSUE TITLE
Cached translations get overwritten by inexistent translations with !$fallback

### ISSUE THREAD

**Issue by schelmo** [vinkla/translator#59]
```php
App::setLocale('en');
// en is already in the database
$article->translate('en', false)->title; // title from database
// 'nl' is not in the database.
$article->translate('nl', false)->title; // null, since not in database
// get 'en' again
$article->translate('en', false)->title; // is null ...
```
That happens because in setAttribute the cache gets overwritten by current App::getLocale();

**Comment by vinkla** [comment]
Thanks for reporting! Maybe you could create a pull request with a test case that fails?

**Comment by vinkla** [comment]
Pushed a fix for this.

**Comment by schelmo** [comment]
Lol, just wrote a test (+ github down :)). You were faster :-) Thx alot!
This commit could be an issue for some people: 
The locale of laravel has changed to the last called translated locale.
pull request incoming
