### ISSUE TITLE
How can i save multiple translations at once?

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [vinkla/translator#61]
I tried 2 options

"title" => [ "en" => "text", "ru" => "text" ]
and
"en" => [ "title" => "text" ]
"ru" => [ "title" => "text" ]

But it's not working.

**Comment by vinkla** [comment]
You should be able to do something like this.

```php
$model->translations()->createMany([
    ['locale' => 'en', 'title' => 'This is english'],
    ['locale' => 'sv', 'title' => 'Detta är svenska'],
]);
```

**Comment by zvermafia** [comment]
Is there a method to update multiple translations at once too?

**Comment by vinkla** [comment]
@zvermafia try this:

```php
$article->translations()->update($translations);
```

**Comment by zvermafia** [comment]
@vinkla I meant with the array in example for the createMany() method:
```php
$model->translations()->createMany([
    ['locale' => 'en', 'title' => 'This is english'],
    ['locale' => 'sv', 'title' => 'Detta är svenska'],
]);
```

**Comment by vinkla** [comment]
Not sure what your are asking. Please add more information.

**Comment by zvermafia** [comment]
I would like to update translations like below:
```php
$model->translations()->updateMany([
    ['locale' => 'en', 'title' => 'This is english'],
    ['locale' => 'sv', 'title' => 'Detta är svenska'],
]);
```
Simple and without translations ID, is it possible?

P.S.:This way doesn't work: `$article->translations()->update($translations);`
