### ISSUE TITLE
Polymorphic database relations? will it work?

### ISSUE THREAD

**Issue by morloderex** [vinkla/translator#62]
Hello :)

Let's say i wanted to translate more than a single model e.g articles and calender Events models.

Right this package is using HasMany which doesn't allow this sort of multiple models sence we are hardcoding the parent_id to be article etc.

Will this package require much work or just an update to the database table and relation to allow for polymorphic relationships?

**Comment by vinkla** [comment]
You might be overthinking this. The relation table doesn't need to be translated right?

**Comment by vinkla** [comment]
You might be overthinking this. The relation table doesn't need to be translated right?

**Comment by morloderex** [comment]
No i don't think i am.. 
Right now we would need to create multiple tables foreach model we would like to have translated. 

If i have articles and calendar events.. And i want both tables to be translated.. 
Then each model would need a seperate table for it's translations or am i wrong here?

**Comment by vinkla** [comment]
I totally agree having too many tables stinks. If you want to put your translations within a JSON column I suggest you to look at [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) by @freekmurze.

**Comment by morloderex** [comment]
Would it be possible for a future version of this package maybe to use a polymorphic relationship?

**Comment by vinkla** [comment]
Maybe, haven't currently planned anything yet.
